name: demo-legacy-catalog # Name of the Catalog Entry
description: |
  Something here
  # Description of the Catalog Entry
version: v0.1.1 # Version of the Catalog to be used
category: Application # Category to be used for searching catalog entries
maintainer: Marcelo Santos # The maintainer of the catalog entry
license: MIT # The license
projectURL: http://demo-legacy.marcelsud.com # A URL related to the catalog entry
